kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-openshift-gitops-argocd-application-controller-additonal
rules:
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - secrets
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - serviceaccounts
  - verbs:
      - '*'
    apiGroups:
      - "integreatly.org"
    resources:
      - grafanadatasources
  - verbs:
      - '*'
    apiGroups:
      - "integreatly.org"
    resources:
      - grafanas