apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-base
spec:
  generators:
  - git:
      repoURL: https://github.com/mnlawler/gitops.git
      revision: HEAD
      directories:
      - path: '*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mnlawler/gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'